//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveTechnologies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ArticleID { get; set; }
        public string ArticleHeaderText { get; set; }
        public System.DateTime ArticleDate { get; set; }
        public bool DisplayDate { get; set; }
        public string ArticleText { get; set; }
        public int ArticleOrder { get; set; }
    }
}
