//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InteractiveTechnologies.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Slideshow
    {
        public int SlideID { get; set; }
        public int ImageID { get; set; }
        public string SlideLink { get; set; }
        public bool Display { get; set; }
        public int SlideOrder { get; set; }
    
        public virtual Image Image { get; set; }
    }
}
